In [24]:
import numpy as np

In [25]:
print("1-length,2-diameter,3-height,4-weight,5-shucked weight,6-viscera weight,7-shall weight,8-age")
i = np.genfromtxt(r"C:\Users\SANDIIP\Downloads\train_extended.csv",delimiter=",",skip_header=1)
i

1-length,2-diameter,3-height,4-weight,5-shucked weight,6-viscera weight,7-shall weight,8-age


array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])


# What is the min and max of length column

In [26]:
max = np.max(i[:,0])
min = np.min(i[:,0])
print(max)
print(min)

7.58349125
0.0



# Difference between the max and min length of the length coloumn

In [27]:
print(max-min)

7.58349125



# Find coloumn wise age

In [28]:
i[:,7]

array([10., 19., 11., ...,  7., 11., 11.])


# Find out all the age whose height is greater than 0.4

In [29]:
i1 = i[i[:,2]>0.4]
i1[:,7]

array([11., 14., 13., ..., 11., 11., 11.])


# What is the avg weight and height of whose age is 10

In [30]:
i2 = i[i[:,7]==10]
avg_height=i2[:,2]
avg_weight=i2[:,3]
print("Average Height is : ",np.mean(avg_height),"\n")
print("Average Weight is : ",np.mean(avg_weight))

Average Height is :  0.3833672856539947 

Average Weight is :  28.243308450511314



# What is total of shell weight

In [31]:
np.sum(i[:,6])

1326845.8295214002


# How many persons belong to each and every unique age

In [34]:
np.unique(i[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))


# What is the difference between shucked weight and viscera weight

In [35]:
i[:,4]-i[:,5]

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])


# What is average height of the persons whose age is between 14 and 19

In [37]:
i3 = (i[:,7]>=14) & (i[:,7]<=19)
np.mean(i3)

0.103115


# What is the average weight if we include shucked weight and viscera weight and shell weight

In [39]:
i4 = i[:,4]+i[:,5]+i[:,6]
np.mean(i4)

21.616780352404746